// بيانات الترجمة
const translations = {
    ar: {
        "club-name": "نادي CROWN",
        "club-description": "للأنشطة الاقتصادية والاجتماعية والإنسانية والرياضية",
        "follow-us": "تابعنا على الإنستغرام",
        "personal-info": "المعلومات الشخصية",
        "first-name": "الاسم الأول",
        "first-name-error": "يرجى إدخال الاسم الأول",
        "last-name": "الاسم الأخير",
        "last-name-error": "يرجى إدخال الاسم الأخير",
        "cin": "رقم بطاقة التعريف الوطنية (CIN)",
        "cin-error": "يرجى إدخال رقم بطاقة التعريف الوطنية",
        "massar": "رقم مسار",
        "massar-error": "يرجى إدخال رقم مسار صحيح",
        "email": "البريد الإلكتروني الجامعي",
        "email-error": "يرجى إدخال بريد إلكتروني جامعي صحيح",
        "phone": "رقم الهاتف",
        "phone-error": "يرجى إدخال رقم هاتف صحيح",
        "major": "التخصص",
        "major-error": "يرجى إدخال تخصصك",
        "year": "سنة الدراسة",
        "select-year": "اختر السنة",
        "first-year": "سنة أولى",
        "second-year": "سنة ثانية",
        "third-year": "سنة ثالثة",
        "fourth-year": "سنة رابعة",
        "graduate": "دراسات عليا",
        "year-error": "يرجى اختيار سنة الدراسة",
        "interests": "اهتمامات النادي",
        "activities-label": "اختر مجالات الأنشطة التي تهمك",
        "economic-activities": "الأنشطة الاقتصادية",
        "social-activities": "الأنشطة الاجتماعية",
        "human-activities": "الأنشطة الإنسانية",
        "sport-activities": "الأنشطة الرياضية",
        "activities-error": "يرجى اختيار مجال نشاط واحد على الأقل",
        "sport-options-title": "اختر الرياضة التي تفضل",
        "volleyball": "الكرة الطائرة",
        "basketball": "كرة السلة",
        "sport-error": "يرجى اختيار رياضة واحدة",
        "interest": "ما الذي يثير اهتمامك في نادينا؟",
        "interest-error": "يرجى إخبارنا بما يثير اهتمامك في نادينا",
        "experience": "الخبرة السابقة (إن وجدت)",
        "additional-info": "معلومات إضافية",
        "availability": "متى تكون متاحاً عادةً للاجتماعات؟",
        "weekday-mornings": "صباح أيام الأسبوع",
        "weekday-afternoons": "بعد ظهر أيام الأسبوع",
        "weekday-evenings": "مساء أيام الأسبوع",
        "weekends": "عطلات نهاية الأسبوع",
        "availability-error": "يرجى اختيار مدى توافرك",
        "hear-about": "كيف سمعت عنا؟",
        "select-option": "اختر خياراً",
        "friend": "صديق",
        "professor": "أستاذ",
        "social-media": "وسائل التواصل الاجتماعي",
        "poster": "ملصق/نشرة",
        "university-website": "موقع الجامعة",
        "club-fair": "معرض الأندية",
        "other": "آخر",
        "mailing-list": "أرغب في تلقي تحديثات النادي عبر البريد الإلكتروني",
        "whatsapp-updates": "أرغب في تلقي تحديثات النادي عبر واتساب",
        "agree": "أوافق على شروط وأحكام النادي",
        "agree-error": "يجب الموافقة على الشروط والأحكام",
        "submit": "تقديم التسجيل",
        "success-title": "شكراً لتسجيلك!",
        "success-message": "لقد استلمنا طلبك وسنتواصل معك قريباً بمزيد من المعلومات."
    },
    fr: {
        // ... French translations
    },
    en: {
        // ... English translations
    }
};

// باقي كود JavaScript سيأتي هنا...
// ... (أضف باقي كود JavaScript من الإصدار السابق)